# Site
repository: marspark00/marspark00.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 박대원 / DAEWON PARK
title: 서버 백엔드 엔지니어
email: marspark00@gmail.com
website: marspark00.github.io

# Dark Mode (true/false/never)
darkmode: true 

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  게임 서버와 웹/앱 서비스 백엔드 개발자로서 <mark>오디션</mark>(PC), <mark>WIA</mark>(오디션3, PC), <mark>클럽 오디션</mark>(모바일), <mark>도시어부M</mark>(모바일) 등의 프로젝트에서 개발 작업을 해왔습니다.  
  C++, MSSQL, Node.js, Java, MariaDB, Redis, AWS, Linux 등을 사용하여 프로덕션 서비스를 설계, 개발, 운영한 경험으로 확장성과 유지 보수성이 높은 백엔드 아키텍처와 패턴을 위해 언제나 고민하고 있습니다.  
  항상 백엔드 개발의 정점을 찍고 싶다는 목표를 가지고 다양한 기술을 학습하거나 사용하고 경험을 쌓고 있습니다.  
  서비스 개발이란 결국 개발과 비즈니스와의 <mark>커뮤니케이션</mark>이 <mark>가장 중요</mark>하다고 생각하고 있습니다.   
  능동적이고 적극적인 커뮤니케이션으로 문제 해결과 비즈니스 발전을 위해 뛰어듭니다.  
  이러한 점을 바탕으로 <mark>더 좋은 개발자</mark>로서 <mark>성장</mark>하기 위해 더 치열하게 <mark>학습</mark>하고, <mark>경험</mark>하고, <mark>노력</mark>하고 있습니다.  


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Certificate Section
# certificate_title: Certificate

# More Section
more_title: Etc
more_content: | # this will include new lines to allow paragraphs
  병역 사항
   - 2000.08 ~ 2002.12 해군 병장 만기제대
  
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
